### ISSUE TITLE
Slow Download Speed

### ISSUE THREAD

**Issue by g10drasingh** [Ak500k/termux-ydl#2] opened 2022-01-12 21:10 UTC
Hei the download speed is less than 100 KiB/s for all downloads. Any fix upcoming for this ?

![IMG_20220113_025448](https://user-images.githubusercontent.com/14206136/149221873-d3a3fd02-d966-44aa-a724-85054451a284.jpg)

**Comment by Ak500k** [comment] 2022-01-13 06:06
working on it, it will be fixed soon

**Comment by Ak500k** [comment] 2022-01-13 07:40
The issue is fixed now, run the script again::  
```shell
clear; curl -s -L https://bit.ly/39XXwxm | bash
```

**Comment by g10drasingh** [comment] 2022-01-13 08:18
The speed is far better than before but it fluctuates too often. In the image below, you can see, the download speed different at different time.

![Screenshot_2022-01-13-13-59-11-780_com termux](https://user-images.githubusercontent.com/14206136/149291889-8d4b6c91-9a0b-4518-84cd-9da9ff6986f7.jpg)

**Comment by Ak500k** [comment] 2022-01-13 08:21
DM me on Instagram:: https://www.instagram.com/geeky.ak/

**Closed** 2022-01-13 09:22 UTC
